export enum SearchParameters {
  ACTION_ID = 'actionId',
  ACTION_RUN_ID = 'actionRunId',
  ACTIVITY_ID = 'activityId',
  CONSTRAINT_ID = 'constraintId',
  MODEL_ID = 'modelId',
  REASON = 'reason',
  REDIRECT_TO = 'redirectTo',
  SIMULATION_DATASET_ID = 'simulationDatasetId',
  SNAPSHOT_ID = 'snapshotId',
  SPAN_ID = 'spanId',
  SPEC_ID = 'specId',
  VIEW_ID = 'viewId',
  SIDEBAR_TAB = 'sidebarTab',
  START_TIME = 'startTime',
  END_TIME = 'endTime',
  REVISION = 'revision',
  SEQUENCE_ID = 'sequenceId',
  LINE_NUMBER = 'lineNum',
  WORKSPACE_ID = 'workspaceId',
}
